### PR TITLE
Run tests with a separate profile, fixes #213

### LINKED ISSUE #213: Selenium tests need to use a new temporary profile
Right now if you run
`npm test`
the tests pass, but if you run that command again, they will fail.

This is most likely because the tests assume that the database is fresh (ie. with no existing users in it), and after the first run there are users so the default behavior for some pages change.

### PR DESCRIPTION
**Pull request by mikehenrty**

### CODE REVIEW

File: tools/execute-selenium-tests [hunk 1]
```diff
@@ -0,0 +1,27 @@
...
+$FOXBOX_BINARY -p ${DEBUG_PORT} --profile ${DEBUG_PROFILE} &
+FOXBOX_PID=$!
+while ! nc -z localhost ${DEBUG_PORT}; do sleep 3; done
+popd
+
+# run tests
+BOX_PORT=${DEBUG_PORT} ${PROJECT_HOME}/node_modules/.bin/mocha ${PROJECT_HOME}/test/selenium/*_test.js
+
+# clean up foxbox process
+kill $FOXBOX_PID
```
Comment (hfiguiere) [inline tools/execute-selenium-tests:32]: Can we also delete the temporary profile? Or is there a good reason to not...

**Comment by hfiguiere** [comment]
This should also help for issue #237.

@mikehenrty do you mind rebasing and updating the PR so we can get this reviewed? (it doesn't apply cleanly). I'd love to see this landed.

File: tools/execute-selenium-tests (hunk 1 above)
Comment (mikehenrty) [inline tools/execute-selenium-tests:32]: I was thinking about keeping it, in case someone wanted to run Link against it and do some manual debugging of what happened.

**Comment by mikehenrty** [comment]
I'll pick this up today, thanks Hub

**Comment by mikehenrty** [comment]
@ferjm, @npark-mozilla, review?

File: src/controller.rs [hunk 2]
```diff
@@ -82,9 +82,10 @@ impl FoxBox {
                hostname: Option<String>,
                http_port: u16,
                ws_port: u16,
-               tls_option: TlsOption) -> Self {
-        let profile_service = ProfileService::new(None);
+               tls_option: TlsOption,
+               directory: Option<String>) -> Self {
```
Comment (ferjm) [inline src/controller.rs]: Instead of a `Option` we can make `directory` a `enum` like:

``` rust
pub enum ProfilePath {
  Default,
  Custom(String)
}
```

and change https://github.com/fxbox/foxbox/blob/d8ccbfa0da2d7c1a0fb74c38fd481210f3216e98/src/profile_service.rs#L27 to use it as well.

File: src/main.rs [hunk 3]
```diff
@@ -102,13 +102,14 @@ use std::sync::atomic::{ AtomicBool, Ordering, ATOMIC_BOOL_INIT };
...
 docopt!(Args derive Debug, "
-Usage: foxbox [-v] [-h] [-l <hostname>] [-p <port>] [-w <wsport>] [-r <url>] [-i <iface>] [-t <tunnel>] [-s <secret>] [--disable-tls] [--remote-name <hostname>] [-c <namespace;key;value>]...
+Usage: foxbox [-v] [-h] [-l <hostname>] [-p <port>] [-w <wsport>] [-d <profile_dir>] [-r <url>] [-i <iface>] [-t <tunnel>] [-s <secret>] [--disable-tls] [--remote-name <hostname>] [-c <namespace;key;value>]...
 
 Options:
     -v, --verbose            Toggle verbose output.
     -l, --local-name <hostname>    Set local hostname. Linux only. Requires to be a member of the netdev group.
     -p, --port <port>        Set port to listen on for http connections. [default: 3000]
     -w, --wsport <wsport>    Set port to listen on for websocket. [default: 4000]
+    -d, --profile <path>     Set profile path [default: $HOME/.local/share/foxbox]
```
Comment (ferjm) [inline src/main.rs]: Can we use `$XDG_DATA_HOME` instead of another command line option?

Check https://github.com/fxbox/foxbox/blob/d8ccbfa0da2d7c1a0fb74c38fd481210f3216e98/src/profile_service.rs#L28

@fabricedesre wdyt?

**Comment by mikehenrty** [comment]
Whoops, just found a bug. Running Link without specifying a profile folder creates a `$HOME` folder in the cwd. Not good, I'm investigating now.

Edit: Fixed.

File: src/main.rs (hunk 3 above)
Comment (mikehenrty) [inline src/main.rs]: My thinking here is that `XDG_DATA_HOME` is a special thing, and that someone might want to specify a profile outside of their `XDG_DATA_HOME` at some point.

File: tools/execute-selenium-tests (hunk 1 above)
Comment (hfiguiere) [inline tools/execute-selenium-tests:32]: Fair enough. Or maybe only in case of failure. That can be fixed later if it is too much cluttering.

File: src/main.rs (hunk 3 above)
Comment (hfiguiere) [inline src/main.rs]: No, you don't want to mess with `$XDG_DATA_HOME`.

**Comment by nojunpark** [comment]
@JohanLorenzo r? as well

**Comment by hfiguiere** [comment]
@fabricedesre we need this PR for #240 r?

File: tools/execute-selenium-tests [hunk 4]
```diff
@@ -0,0 +1,27 @@
...
+CURRENT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+PROJECT_HOME="$CURRENT_PATH/.."
+FOXBOX_BINARY="$PROJECT_HOME/target/debug/foxbox"
+
+DEBUG_HOST=${BOX_LOCAL_NAME:-'localhost'}
+DEBUG_PORT=${BOX_PORT:-3331}
+DEBUG_PROFILE="$HOME/.local/share/foxbox-debug"
+
+# clean up residual profile
+rm -rf ${DEBUG_PROFILE}
```
Comment (JohanLorenzo) [inline tools/execute-selenium-tests]: Nit: Double-quote `$DEBUG_PROFILE`. If somebody has a HOME path that contains a space, this line won't work.

File: tools/execute-selenium-tests [hunk 5]
```diff
@@ -0,0 +1,27 @@
...
+
+# build and launch foxbox daemon
+pushd ${PROJECT_HOME}
+cargo build
+$FOXBOX_BINARY -l ${DEBUG_HOST} -p ${DEBUG_PORT} --disable-tls --profile ${DEBUG_PROFILE} &
```
Comment (JohanLorenzo) [inline tools/execute-selenium-tests]: What is the pro of `cargo build` + call executable, compared to `cargo run`?

File: tools/execute-selenium-tests [hunk 6]
```diff
@@ -0,0 +1,27 @@
...
+FOXBOX_PID=$!
+popd
+
+# run tests
+BOX_PORT=${DEBUG_PORT} ${PROJECT_HOME}/node_modules/.bin/mocha ${PROJECT_HOME}/test/selenium/*_test.js
```
Comment (JohanLorenzo) [inline tools/execute-selenium-tests]: Nit: Double-quotes on `${PROJECT_HOME}/node_modules/.bin/mocha` and `${PROJECT_HOME}/test/selenium/`. The project might be in a folder that contains a space

File: .travis.yml [hunk 7]
```diff
@@ -32,5 +32,5 @@ script:
     - cargo build # Linter is also executed here
     - cargo test
     - jshint static/main/js/*.js static/setup/js/*.js test/selenium/*.js test/integration/lib/*.js test/integration/test/*.js
-    - npm run test-integration # starts foxbox and kills it within the test script
-    - (cargo run -- -l $BOX_LOCAL_NAME -p $BOX_PORT --disable-tls &> /dev/null &) ; npm run test-selenium
+    - npm run test-integration
+    - npm run test-selenium
```
Comment (JohanLorenzo) [inline .travis.yml:36]: Nice clean up :)

File: src/main.rs [hunk 8]
```diff
@@ -102,13 +102,14 @@ use std::sync::atomic::{ AtomicBool, Ordering, ATOMIC_BOOL_INIT };
...
 docopt!(Args derive Debug, "
-Usage: foxbox [-v] [-h] [-l <hostname>] [-p <port>] [-w <wsport>] [-r <url>] [-i <iface>] [-t <tunnel>] [-s <secret>] [--disable-tls] [--remote-name <hostname>] [-c <namespace;key;value>]...
+Usage: foxbox [-v] [-h] [-l <hostname>] [-p <port>] [-w <wsport>] [-d <profile_dir>] [-r <url>] [-i <iface>] [-t <tunnel>] [-s <secret>] [--disable-tls] [--remote-name <hostname>] [-c <namespace;key;value>]...
 
 Options:
     -v, --verbose            Toggle verbose output.
     -l, --local-name <hostname>    Set local hostname. Linux only. Requires to be a member of the netdev group.
     -p, --port <port>        Set port to listen on for http connections. [default: 3000]
     -w, --wsport <wsport>    Set port to listen on for websocket. [default: 4000]
+    -d, --profile <path>     Set profile path
```
Comment (JohanLorenzo) [inline src/main.rs]: If I didn't see the PR, I wouldn't be 100% sure of what a profile represents. Maybe we could make the message more explicit? What do you think of `Set profile path to store user's data`?

Comment (fabricedesre) [inline src/main.rs]: Please switch to -P instead of -d

File: src/controller.rs (hunk 2 above)
Comment (fabricedesre) [inline src/controller.rs]: Yep, good idea.

**Comment by fabricedesre** [comment]
Fine with me if you address all the comments from various people ;)

File: tools/execute-selenium-tests (hunk 1 above)
Comment (npark-mozilla) [inline tools/execute-selenium-tests]: Strange, so when I execute the foxbox, it dies with the error 
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("failed to lookup address information: nodename nor servname provided, or not known") }) }', ../src/libcore/result.rs:746

This was fixed when I deleted the -l localhost parameter and issued following command instead:
/Users/g5njpark/GitRepo/foxbox/tools/../target/debug/foxbox -p 3331 --disable-tls --profile /Users/g5njpark/.local/share/foxbox-debug

Ah, so -l is for linux only.  I guess it's good for the travis since it's on Ubuntu, but would there be a quick way to check for the environment in ./execute-selenium-tests?  if so we can also use npm run selenium-tests on mac.

**Comment by nojunpark** [comment]
Strange, so when I execute the foxbox, it dies with the error 
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Error { repr: Custom(Custom { kind: Other, error: StringError("failed to lookup address information: nodename nor servname provided, or not known") }) }', ../src/libcore/result.rs:746

This was fixed when I deleted the -l localhost parameter and issued following command instead:
/Users/g5njpark/GitRepo/foxbox/tools/../target/debug/foxbox -p 3331 --disable-tls --profile /Users/g5njpark/.local/share/foxbox-debug

Ah, so -l is for linux only.  I guess it's good for the travis since it's on Ubuntu, but would there be a quick way to check for the environment in ./execute-selenium-tests?  if so we can also use npm run selenium-tests on mac.

Aside from this nit, r+ for me.

**Comment by hfiguiere** [comment]
@npark-mozilla the ````--profile```` isn't about the Firefox profile at all.

**Comment by hfiguiere** [comment]
(deleted my last comment, please ignore the email)

File: tools/execute-selenium-tests (hunk 5 above)
Comment (mikehenrty) [inline tools/execute-selenium-tests]: Since `cargo run` first builds and then forks the foxbox daemon process, it is harder to get the PID of the actual foxbox process (so we can kill it later). We also then have to explicitly wait for the daemon to spin up (using something like netcat) before continuing to the next line. Doing it this way was just cleaner.

File: tools/execute-selenium-tests (hunk 4 above)
Comment (mikehenrty) [inline tools/execute-selenium-tests]: @JohanLorenzo doesn't the double quotes on the definition of DEBUG_PROFILE above cover this?

**Comment by mikehenrty** [comment]
@fabricedesre or @ferjm, r?

File: src/controller.rs [hunk 9]
```diff
@@ -289,9 +290,12 @@ describe! controller {
     before_each {
         use stubs::service::ServiceStub;
         use tls::TlsOption;
+        use profile_service::ProfilePath;
 
         let service = ServiceStub;
-        let controller = FoxBox::new(false, Some("foxbox".to_owned()), 1234, 5678, TlsOption::Disabled);
+        let controller = FoxBox::new(
+          false, Some("foxbox".to_owned()), 1234, 5678,
+                      TlsOption::Disabled, ProfilePath::Default);
```
Comment (jedireza) [inline src/controller.rs:298]: nit: line up args

``` rust
let controller = FoxBox::new(false,
                             Some("foxbox".to_owned()),
                             1234,
                             5678,
                             TlsOption::Disabled,
                             ProfilePath::Default);
```

File: src/controller.rs [hunk 10]
```diff
@@ -316,7 +320,9 @@ describe! controller {
             assert_eq!(controller.get_http_root_for_service("1".to_string()),
                        "http://foxbox.local:1234/services/1/");
 
-            let controller = FoxBox::new(false, Some("foxbox".to_owned()), 1234, 5678, TlsOption::Enabled);
+            let controller = FoxBox::new(false, Some("foxbox".to_owned()),
+                                         1234, 5678, TlsOption::Enabled,
+                                         ProfilePath::Default);
```
Comment (jedireza) [inline src/controller.rs:325]: nit: i like one arg per line when they're broken up

File: src/service_router.rs [hunk 11]
```diff
@@ -69,8 +69,11 @@ describe! service_router {
         use iron_test::request;
         use mount::Mount;
         use tls::TlsOption;
+        use profile_service::ProfilePath;
 
-        let controller = FoxBox::new(false, Some("localhost".to_owned()), 1234, 5678, TlsOption::Disabled);
+        let controller = FoxBox::new(false, Some("localhost".to_owned()),
+                                     1234, 5678, TlsOption::Disabled,
+                                     ProfilePath::Default);
```
Comment (jedireza) [inline src/service_router.rs:76]: nit: i like one arg per line when they're broken up

File: src/profile_service.rs [hunk 12]
```diff
@@ -104,7 +110,8 @@ fn test_custom_profile() {
     let profile_path = String::from(profile_dir.into_path()
                                     .to_str().unwrap());
 
-    let profile = ProfileService::new(Some(profile_path.to_owned()));
+    let profile = ProfileService::new(ProfilePath::Custom(profile_path
+                                                          .clone()));
```
Comment (jedireza) [inline src/profile_service.rs:114]: nit: since we're using another line, can we make it more readable? maybe making a variable out of one of those inner values?

``` rust
let custom_path = ProfilePath::Custom(profile_path.clone());
let profile = ProfileService::new(cloned_path);
```

File: src/controller.rs (hunk 9 above)
Comment (mikehenrty) [inline src/controller.rs:298]: Hmmm, this isn't the convention I've seen. Do you guys have a style guide somewhere?

File: src/profile_service.rs (hunk 12 above)
Comment (mikehenrty) [inline src/profile_service.rs:114]: The reason we are doing the clone is because the ownership of this string gets passed to the profile service, and we need to do a comparison with this string in our assert statement here below. So doing a clone before assigning the string to a variable runs into the same ownership problem this clone is meant to address.

Comment (mikehenrty) [inline src/profile_service.rs:114]: Oh I see what you mean. That would work too. Although the convention seems to be not assigning state variables for this ownership management stuff. A style guide would help here, but I guess you guys are still figuring that out.

File: src/controller.rs (hunk 9 above)
Comment (jedireza) [inline src/controller.rs:298]: I see it in Servo
https://github.com/servo/webrender/blob/2a71ccb0249601b25ef156f9a585a001c8d606cb/src/render_backend.rs#L152-L158
